#ifndef FAULT_CODES_H
#define FAULT_CODES_H

#include <stdint.h>

typedef enum{
    FAULT_HEALTHY = 0,
    FAULT_ESTOP, //1
    FAULT_PRESSURE1_SENSOR,//2
    FAULT_PRESSURE2_SENSOR,//3
    FAULT_TEMPERATURE1_SENSOR,//4
    FAULT_TEMPERATURE2_SENSOR,//5
    FAULT_TEMPERATURE3_SENSOR,//6
    FAULT_TEMPERATURE4_SENSOR,//7
    FAULT_LIQUID_COMPRESSOR,//8
    FAULT_TEMPERATURE_DEVIATION,//9
    FAULT_OUTLET_TEMPERATURE_OVER,//10
    FAULT_OUTLET_PRESSURE_OVER, //11
    FAULT_EVAPERATOR_FREEZING, //12
    FAULT_UNDER_PRESSURE, //13
} errorCode;

typedef enum{
    HEALTHY = 0,
    FAULT,
} healthState;


#endif
